# Generated by Django 3.0 on 2019-12-07 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laporan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Submit')),
                ('judul', models.CharField(max_length=50)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Sudah Masuk'), (2, 'Ditanggapi'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')], default=0)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='masterdata.Kategori')),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to='masterdata.Kecamatan')),
                ('pelapor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laporan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.BooleanField(choices=[(1, 'Setuju'), (0, 'Tidak Setuju')])),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='laporan.Laporan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.TextField(max_length=1024)),
                ('laporan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='laporan.Laporan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
