# Generated by Django 2.2.7 on 2019-12-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20)),
                ('daerah', models.CharField(max_length=25)),
                ('telepon', models.CharField(max_length=15)),
                ('jabatan', models.CharField(max_length=20)),
            ],
        ),
    ]
