# Generated by Django 2.2.7 on 2019-12-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserdata',
            name='jabatan',
        ),
        migrations.AddField(
            model_name='additionaluserdata',
            name='dinas',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserdata',
            name='nama',
            field=models.CharField(default='tegar', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionaluserdata',
            name='daerah',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserdata',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserdata',
            name='telepon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
