# Generated by Django 3.0 on 2019-12-07 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kecamatan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tinggal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kedinasan',
            name='pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kedinasan', to=settings.AUTH_USER_MODEL),
        ),
    ]
