# Generated by Django 3.0 on 2019-12-07 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterdata', '0002_auto_20191207_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformasiTambahanUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=20)),
                ('telepon', models.CharField(max_length=15)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pegawai', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='kecamatan',
            name='user',
        ),
        migrations.DeleteModel(
            name='Pegawai',
        ),
    ]
