# Generated by Django 3.0 on 2019-12-07 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_auto_20191207_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kedinasan',
            name='pegawai',
        ),
    ]
