# Generated by Django 3.0 on 2019-12-07 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_remove_kedinasan_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='informasitambahanuser',
            name='kedinasan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pegawai', to='masterdata.Kedinasan'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='kecamatan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='masterdata.Kecamatan'),
        ),
    ]
