# Generated by Django 3.0 on 2019-12-07 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0005_auto_20191207_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='kecamatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='masterdata.Kecamatan'),
        ),
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='kedinasan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pegawai', to='masterdata.Kedinasan'),
        ),
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='informasitambahanuser',
            name='telepon',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
