# Generated by Django 2.2.7 on 2019-12-01 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Lapor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='District',
            new_name='Kecamatan',
        ),
        migrations.DeleteModel(
            name='Custom_user',
        ),
        migrations.RemoveField(
            model_name='komentar',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='laporan',
            name='datetime',
        ),
        migrations.AddField(
            model_name='komentar',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laporan',
            name='waktu',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laporan',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='judul',
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Telah Diterima'), (2, 'Respon'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')]),
        ),
        migrations.AlterField(
            model_name='vote',
            name='pilihan',
            field=models.BooleanField(choices=[(1, 'Saya setuju'), (0, 'Saya tidak setuju')]),
        ),
    ]
