# Generated by Django 2.2.7 on 2019-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapor', '0002_auto_20191201_1419'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kategori',
        ),
        migrations.DeleteModel(
            name='Kecamatan',
        ),
        migrations.AddField(
            model_name='laporan',
            name='kecamatan',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laporan',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Telah Diterima'), (2, 'Respon'), (3, 'Sedang Dikerjakan'), (4, 'Selesai')], default=1),
        ),
    ]
