# Generated by Django 2.2.7 on 2019-12-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapor', '0003_auto_20191201_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='laporam',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='komentar',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='laporan',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='nama',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='komentar',
            name='isi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
