# Generated by Django 2.2.7 on 2019-12-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapor', '0004_auto_20191201_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='komentar',
            name='isi',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
    ]
