# Generated by Django 2.2.7 on 2019-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lapor', '0005_auto_20191201_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('kedinasan', models.CharField(max_length=50)),
            ],
        ),
    ]
